### ISSUE TITLE
An error on node v10.13.0 in macOS v10.13.6 : UnhandledPromiseRejectionWarning: Error: Exited with code 1

### ISSUE THREAD

**Issue by cag2050** [sindresorhus/open#112]
Error message:
```
(node:70665) UnhandledPromiseRejectionWarning: Error: Exited with code 1
    at ChildProcess.cp.once.code (/Users/user_name/Documents/WebstormProjects/project_name/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
(node:70665) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:70665) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by revolutionnaire** [comment]
I get the same error also after running `ng serve --open` for the first time:
`(node:31326) UnhandledPromiseRejectionWarning: Error: spawn /home/chronos/user/graffitis/node_modules/opn/xdg-open EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:31326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31326) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by twboc** [comment]
same here

(node:9735) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 1
(node:9735) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jkawamoto** [comment]
Perhaps, you need to catch the error with something like this:

```javascript
opn('http://sindresorhus.com').catch(err => console.error(err));
```

**Comment by danealiu** [comment]
> Perhaps, you need to catch the error with something like this:
> 
> ```js
> opn('http://sindresorhus.com').catch(err => console.error(err));
> ```

do like this, but nothing help

**Comment by sindresorhus** [comment]
Closing as this is most likely a usage error. If it's actually a problem, please submit a failing test.
