### ISSUE TITLE
Add the possibility for a fallback browser.

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/open#119]
If it's set to open a browser window in eg. `Safari` but this browser is not available on another dev's computer, I'd love to be able to set a fallback browser like `Google Chrome`.

**Comment by sindresorhus** [comment]
Why are you setting a preferred browser? Would be better to just not specify a browser and let the system use the user-default browser.

**Comment by mesqueeb** [comment]
The reason is that I use Safari as default browser for my computer for browsing the web.
When I develop I prefer Google Chrome or Brave Browser (same chromium dev tools as chrome).

When I eg. set my dev environment to open in Brave Browser when my dev server starts running, my colleagues couldn't launch the dev server anymore because they didn't have Brave Browser.
When I revert back to `true` to the default browser, every time it will open in Safari for me, which is very annoying. 😃

**Comment by sindresorhus** [comment]
You are trying to push your preferences on your team mates. I don't buy your use-case. You should instead use an app like https://www.choosyosx.com/

**Comment by mesqueeb** [comment]
I just re-read my post and it can be interpreted as that. I see now. 
However I wanted to achieve the opposite really. 
If the fall back browser can be the system default browser it would work for everyone. 
Now if I do set a specific browser it doesn't work for people who don't have that browser, that's all. 
Setting fall back to default browser seems like a logical choice.. 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
