### ISSUE TITLE
opn works just fine on localhost but throws an error on the real server

### ISSUE THREAD

**Issue by uo2** [sindresorhus/open#121]
Hello @sindresorhus,

I'm developing a small PDF-generator using puppeteer (headless Chrome). In the beginning, I tested the generator on localhost:3000 and `opn` worked great. However, after deploying on the server (Ubuntu 16.04 + Nginx + WordPress), the application crashed on the line that use `opn`.

When I call this code:
```js
const express = require('express');
const fs = require('fs');
const puppeteer = require('puppeteer'); // the package to generate pdf
const opn = require('opn');

const app = express();
let invoiceNumber;

app.post('/generate', (req, res) => {
    invoiceNumber = req.body.data; // receiving invoice number via AJAX query
});

app.get('/generate', async (req, res) => {
	try {
               // code for pdf generation
		const url = 'https://flogdev.com/invoice_new/invoice.html';
		const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
		const page = await browser.newPage();
		await page.goto(url, {waitUntil: 'networkidle2'});
		await page.pdf({path: `invoice_${invoiceNumber}.pdf`, format: 'A4'});
		
		await browser.close();
		console.log(`The invoice number ${invoiceNumber} has been generated.`);
                // errors occur on calling `opn`
		await opn(`https://flogdev.com/invoice_new/invoice_${invoiceNumber}.pdf`);		
		
		console.log('Redirected.');
		
		// the code to delete a generated file from the server after 10 seconds
		setTimeout(() => {
			fs.unlink(`invoice_${invoiceNumber}.pdf`, (err) => {
				if (err) throw err;
			});
		}, 120000);
	} catch (err) {
		console.log(err);
	}
});
```

the command line shows this error:

> Error: Exited with code 3
    at ChildProcess.cp.once.code (/var/www/html/invoice_new/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:616:12)

I've tried to fix this by adding some additional parameters to a function call:
`opn('https://flogdev.com/invoice_new/invoice_${invoiceNumber}.pdf', {app: ['firefox', '--incognito']});`

This time the terminal showed another error:

> { Error: spawn firefox ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn firefox',
  path: 'firefox',
  spawnargs:
   [ '--incognito',
     'https://flogdev.com/invoice_new/invoice_260320195161.pdf' ] }

So, I just deleted the `--incognito` option. 
`opn('https://flogdev.com/invoice_new/invoice_${invoiceNumber}.pdf', {app: 'firefox'});`

The error changed a bit:

> events.js:167
      throw er; // Unhandled 'error' event
      ^ Error: spawn firefox ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

The same thing with `chrome` instead of `firefox`.

So, could you help me with this? Why `opn` works just fine on localhost but doesn't work on a real server?

**Comment by sindresorhus** [comment]
I'm not sure why you're trying to use `open` on the server, but I'm pretty sure you're using it incorrectly. `open` is meant to open things locally for users. What problem are you trying to solve?
