### ISSUE TITLE
New version (6.0.0) is still flagged as critical severity vulnerability

### ISSUE THREAD

**Issue by siltus** [sindresorhus/open#122]
Hi,
I've upgraded opn 5.x package to the new open 6.0.0 version, and as soon as i run `npm install` I get an audit warning about the package - [warn.txt](https://github.com/sindresorhus/open/files/3019607/warn.txt).

This is probably still related to the old versions of "open", which why we all have been using "opn" in the first place :)

Might be a good idea to resolve this now obsolete warning (probably need to talk with NPM guys).

**Comment by RandomByte** [comment]
The [advisory on open](https://www.npmjs.com/advisories/663) has been updated and version 6.0.0 is not listed as affected anymore.

```
❯ npm i open

+ open@6.0.0
added 2 packages from 1 contributor and audited 2 packages in 0.623s
found 0 vulnerabilities
```

I think this issue can be closed.

**Comment by siltus** [comment]
I can confirm what @RandomByte wrote. Closing
