### ISSUE TITLE
Unexpected identifier path

### ISSUE THREAD

**Issue by WinfredMa** [sindresorhus/open#123]
I got the following error message when I installed the latest version(open@6.0.0) in windows 10.

node_modules\open\index.js:11
const wslToWindowsPath = async
 path => {
 ^^^^
SyntaxError: Unexpected identifier

**Comment by WinfredMa** [comment]
Local babel version issue.

**Comment by piotrmackiewicz** [comment]
@WinfredMa Hello, can you explain what was excatly the problem with babel? I have the same issue but can't figure out what's the problem.

**Comment by bhaskar-nair2** [comment]
I got this wile running my pipeline with docker.. Changing node version to latest does the job..

**Comment by wuyuedefeng** [comment]
I alse have this problem, with `node 6.10.0`
