### ISSUE TITLE
Not working with node 6 anymore

### ISSUE THREAD

**Issue by pm-radu** [sindresorhus/open#125]
Hi,

In the last release, you switched to using `async/await` which caused my node 6 project to stop working. I noticed that because your package is used by `live-server` (pointing to your `latest`).

I added more details here:
https://github.com/tapio/live-server/issues/305

Is there any solution for using it with node 6?

Thanks

**Comment by sindresorhus** [comment]
You'll have to wait for them to fix it. The problem is all theirs when they mis-use semver by using `latest`.
