### ISSUE TITLE
Arbitrary Command Injection

### ISSUE THREAD

**Issue by Stradivario** [sindresorhus/open#132]
https://app.snyk.io/test/npm/@rxdi/hapi/0.2.20#npm:open:20180512

![Screenshot from 2019-05-07 17-15-40](https://user-images.githubusercontent.com/19847933/57306580-c1a5ba00-70eb-11e9-92c9-99a89c4e4a48.png)

https://app.snyk.io/vuln/npm:open:20180512

**Comment by sindresorhus** [comment]
Sorry, but Snyk is a bullshit company. No one should take their reports seriously. `open` isn't even using `exec()` as mentioned in the report.

**Comment by sindresorhus** [comment]
https://twitter.com/sindresorhus/status/1123990254648795136

**Comment by benjifin** [comment]
Hey, so indeed the fact that this package used the old `open` name is what caused the mis-tagging of what is a really serious vuln in the old open package, thanks @Stradivario for pointing this out so we can fix it - we'll have the reclassification in place by the eod, and will include a warning that the package has changed from version 6.0.0 onwards.

Trying to track all the changes people make in an open-source system is obviously pretty difficult, so it's always helpful to get constructive feedback so we can fix things when mistakes are made, or people change things :)
