### ISSUE TITLE
open inside Gitlab CI

### ISSUE THREAD

**Issue by Meemaw** [sindresorhus/open#137]
I'm trying to use open inside Gitlab CI to authenticate my google client through OAuth2 flow for e2e tests.

To do that I have to open URL that looks like this:
```https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.readonly&login_hint=meshwatchtesting%40gmail.com&response_type=code&client_id=710109800661-2sat5censue1km83i1vsna8m9na87b66.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Foauth2callback```

Before that, temporary server is started on that port to intercept the OAuth2 callback. CI output looks like this:
```
[googleapis]: Server listening on port:  3001
[googleapis]: Opening authorization URL in browser:  https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.readonly&login_hint=meshwatchtesting%40gmail.com&response_type=code&client_id=710109800661-2sat5censue1km83i1vsna8m9na87b66.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Foauth2callback
[googleapis]: waiting for OAuth2 callback...
```

It works locally, but it doesnt seem to work inside Gitlab's CI. My question is if there is any known issue about it or is there any way to get a feedback from the library if the URL was actually opened.

Any help would be appreciated.

**Comment by sindresorhus** [comment]
I don't really have an answer for you. Gitlab CI might be blocking the browser or something else. I would, however, not use `open` for this. Seems like just doing a request from Node.js would be better, or even Puppeteer.

**Comment by Meemaw** [comment]
It turned out that `open` wasn't the problem. There were much more that I had to do on "unknnown CI computer" to prove  Google its me. :)
