### ISSUE TITLE
Exit from browser app not captured 

### ISSUE THREAD

**Issue by RichardFoss** [sindresorhus/open#139]
Thanks for this capability!
I am using it in an OSX node.js application. When I do this, I don't see the browser context, but rather just my client app name and my GUI. The client app window is also very small - does not show the whole GUI.

When I exit, the exit is not picked up by:
window.addEventListener("beforeunload", function() {
    socket.emit("clientLeft", clientID);
});

Any way that I can increase the window size and also capture exit?

**Comment by sindresorhus** [comment]
These questions are not related to `open`.
