### ISSUE TITLE
Use system xdg-open when available

### ISSUE THREAD

**Issue by christianbundy** [sindresorhus/open#147]
Hello! I'm trying to package this application with [pkg](https://github.com/zeit/pkg) but there's currently a bug where dependencies (like open) aren't allowed to spawn a process from inside the bundled directory (https://github.com/zeit/pkg/issues/342). I'd love a solution to this problem. The first two things that come to mind:

1. Use the system xdg-open if it's available, falling back to the bundled xdg-open only when necessary.
2. Copy xdg-open to the operating system's temporary directory before trying to execute it so that it can run inside of a virtual filesystem.

Do either of these sound like they'd be useful, or are there better alternatives you could think of? Thanks for your help!

**Comment by sindresorhus** [comment]
Are you using the latest version? We now check if the local one is executable before we decide to use it: https://github.com/sindresorhus/open/blob/37a769d6073862ab4a46c00b1a21b2ba814e68cf/index.js#L87

**Comment by christianbundy** [comment]
Yep, I'm on `open@6.4.0`. I don't think the virtual filesystem is changing the file mode, it's just breaking when it actually gets executed. If you'd like you can test with [my repo](https://github.com/fraction/oasis/tree/add-pkg), running `npm start` opens the browser fine but `npm run build && ./build/oasis-linux` throws an error.

I'm currently catching the error here:

https://github.com/fraction/oasis/blob/234641a2c42894b655874567b0e60e485343c114/src/app.js#L139-L142

**Comment by sindresorhus** [comment]
That's for `pkg` to fix then, and it seems like someone is fixing it: https://github.com/zeit/pkg/pull/751
