### ISSUE TITLE
Sometimes does not work in Electron App like VSCode

### ISSUE THREAD

**Issue by Aur3l14no** [sindresorhus/open#151]
For example, markdown files (.md) can be opened from a standalone script like

```
const open = require('open');
open('foobar.md');
```

But when used in a VSCode Extension, it fails.

**Comment by sindresorhus** [comment]
From the top of the readme:

> If need this for Electron, use [`shell.openItem()`](https://electronjs.org/docs/api/shell#shellopenitemfullpath) instead.

VSCode uses Electron.
