### ISSUE TITLE
Open Unable to Connect to localhost on Windows WSL (v. 7.0.0)

### ISSUE THREAD

**Issue by XxX-MLGNoob-XxX** [sindresorhus/open#154]
For some reason I cannot open to my localhost port with the current version of the package (7.0.0). Attempting to do so yields the following error:

`
Windows cannot find '\http://localhost:3000\'. Make sure you typed the name correctly, and then try again.
`

Here is my JavaScript code:

```js
import express from 'express';
import path from 'path';
import open from 'open';

const app = express();
const port = process.env.PORT || 3000;

app.get(['/'], function(req, res) {
  res.sendFile(path.join(__dirname, '../public/index.html'));
});

app.listen(port, function(err) {
  if (err) {
    console.error(err);
  } else {
    console.info(`App listening on port ${port}`);
    open('http://localhost:' + port);
  }
});
```

Note that everything works correctly on version 6.4.0, and I can open to my localhost just fine with that. It's only on 7.0.0 that I'm seeing this issue.

**Comment by sindresorhus** [comment]
// @herberttn

**Comment by btd** [comment]
This is not about really `localhost` problem, you can call open with just `./file.html` and get the same result. Reproduced both in wsl and ps

**Comment by ArthurBiazonMachado** [comment]
The problem is that the url is being enclosed in double quotes to allow spaces and other unmarked characters in the target. As a result, the quotes are getting passed to the browser.

`		// target = `"${target}"`;
		// childProcessOptions.windowsVerbatimArguments = true;
`

Commenting lines 76 and 77 of index.js corrects the issue.

**Comment by ArthurBiazonMachado** [comment]
The problem is that the url is being enclosed in double quotes to allow spaces and other unmarked characters in the target. As a result, the quotes are getting passed to the browser.

```javascript
		// target = `"${target}"`;
		// childProcessOptions.windowsVerbatimArguments = true;
```

Commenting lines 76 and 77 of index.js corrects the issue.

**Comment by herberttn** [comment]
I cannot reproduce the problem. I'm trying `require('open')('http://localhost:7070')` on the Node.js v12 REPL. It correctly opens the browser with the correct URL.

Can you guys post some more details about your setup? Versions, envs, shells, etc.

**Comment by btd** [comment]
@herberttn i created very simple [repro](https://github.com/btd/open-bug) case. Just clone and run `node index`. I used WSL1 and node 10.
<img width="421" alt="Untitled" src="https://user-images.githubusercontent.com/334851/68839646-68819900-06c1-11ea-98ae-6e3a66f2e0cc.png">

**Comment by FKobus** [comment]
@herberttn I can confirm that this bug on Windows 10 + WSL + open 7.0.0 exists. I'm also getting this popup after upgrading to open 7

**Comment by herberttn** [comment]
Thanks @btd and @FKobus, I haven't used WSL all that much recently, so I'll take some time to refresh that knowledge and reproduce this.

**Comment by endiliey** [comment]
Can confirm this is happening

I just upgraded react-scripts to 3.3.0 (which upgraded open v6 to v7) 

Reproducible repo here. https://github.com/endiliey/rengorum

Can only be reproduced in WSL
![image](https://user-images.githubusercontent.com/17883920/70224687-4ccd5800-1780-11ea-9f64-d20c94451be6.png)

**Comment by herberttn** [comment]
> Edit: I think windows too

Hey @endiliey, what do you mean by this? Can you give me some more details?

**Comment by endiliey** [comment]
@herberttn my bad. I tried to reproduce it again, couldn't reproduce it on Windows. Only on WSL for me

**Comment by ArthurBiazonMachado** [comment]
It only happens on WSL, because of some argument handling on Windows that allows arguments to have spaces and other characters. Apparently, it doesn't work for WSL. Lines 76 and 77 of index.js are the culprits.

```javascript
	} else if (process.platform === 'win32' || isWsl) {
		command = 'cmd' + (isWsl ? '.exe' : '');
		cliArguments.push('/s', '/c', 'start', '""', '/b');

		// Always quoting target allows for URLs/paths to have spaces and unmarked characters, as `cmd.exe` will
		// interpret them as plain text to be forwarded as one unique argument. Enabling `windowsVerbatimArguments`
		// disables Node.js's default quotes and escapes handling (https://git.io/fjdem).
		// References:
		// - Issues #17, #44, #55, #77, #101, #115
		// - Pull requests: #74, #98
		//
		// As a result, all double-quotes are stripped from the `target` and do not get to your desired destination.
		target = `"${target}"`;
		childProcessOptions.windowsVerbatimArguments = true;

		if (options.wait) {
			cliArguments.push('/wait');
		}

		if (options.app) {
			if (isWsl && options.app.startsWith('/mnt/')) {
				const windowsPath = await wslToWindowsPath(options.app);
				// eslint-disable-next-line require-atomic-updates
				options.app = windowsPath;
			}

			cliArguments.push(options.app);
		}

		if (appArguments.length > 0) {
			cliArguments.push(...appArguments);
		}
	} else {
```

**Comment by FKobus** [comment]
Did some more testing. So far it looks like it's only happening when you run via WSL.

Regular cmd/bash on Windows ✔️ 
Mac ✔️ 
WSL on Windows ❌

**Comment by herberttn** [comment]
> Did some more testing. So far it looks like it's only happening when you run via WSL.
> 
> ✔️ Regular cmd/bash on Windows
> ✔️ Mac
> ❌ WSL on Windows

Yeah, I've arrived at the same conclusion. The sad part is I've not been able to find **any** documentation that even begins to explain why. I guess we could just check if we're in WSL (as some other caveats already do).

@sindresorhus would you be comfortable with it?

**Comment by Summon528** [comment]
> Yeah, I've arrived at the same conclusion. The sad part is I've not been able to find **any** documentation that even begins to explain why. I guess we could just check if we're in WSL (as some other caveats already do).

If I have to make a guess I will think it is because node thinks it is in Unix, therefore ignore the `windowsVerbatimArguments` option. 

> `windowsVerbatimArguments` \<boolean\> No quoting or escaping of arguments is done on Windows. **Ignored on Unix**. Default: `false`. [source](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback)

**Comment by pluma** [comment]
Just a heads up: this should be fixed now via #164 and #168.

**Comment by FKobus** [comment]
Which release should we expect to this being fixed so we can update accordingly?

**Comment by bodnarbm** [comment]
@FKobus The final PR landed in release [v7.0.2](https://github.com/sindresorhus/open/releases/tag/v7.0.2)

**Comment by karlhorky** [comment]
Nice! @XxX-MLGNoob-XxX can this be closed now?

**Comment by XxX-MLGNoob-XxX** [comment]
@karlhorky can confirm `open` is behaving properly on my WSL now.

Thanks, guys!
