### ISSUE TITLE
can not find program path in windows when specific app option

### ISSUE THREAD

**Issue by tjx666** [sindresorhus/open#158]
below code works well:

```javascript
open(resolve(__dirname, "./test.html"), "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe");
```

But I'm using typescript, as the type definition, I can only use like:

```typescript
open(resolve(__dirname, "./test.html"), {
  app: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
});
```

I try the version of V6.4.0, that version has not this problem.

package version: V7.0.0
OS version: win10 pro  1909
node version: v12.13.1

Then happen the error like screenshot:
![Snipaste_2019-12-12_12-49-50](https://user-images.githubusercontent.com/41773861/70683634-0a56ce80-1cde-11ea-8bc3-fc65a258139d.png)

**Comment by Hongarc** [comment]
@tjx666 Can you check solution #162 ?

**Comment by tjx666** [comment]
@Hongarc  It works.

![Snipaste_2020-01-02_21-35-55](https://user-images.githubusercontent.com/41773861/71669524-e3a12a80-2da7-11ea-86bd-4e565353308d.png)

**Comment by Hongarc** [comment]
You should add double-quotes manual until this PR is merged(or reject with better solution)
