### ISSUE TITLE
Suggest of implementation to support Pkg (in Linux)

### ISSUE THREAD

**Issue by leonardospeca** [sindresorhus/open#159]
Hi, I think that should be a good idea, add an option like 'copyDir' that moves the lib of xdg-open from local to the .cache folder in the home path of the OS, cause some tools like Pkg, show the executable file inside his snapshot as 'Accessible', but can't spawn a child process from there.

**Comment by sindresorhus** [comment]
What is `Pkg`?

**Comment by leonardospeca** [comment]
https://github.com/zeit/pkg

**Comment by leonardospeca** [comment]
Something like:
```
getXdgOpenPath(copyDir = false) {
	const binName = 'xdg-open';
	const binPath = path.resolve(`${__dirname}/${binName}`);
	if (copyDir) {
		copyDir = path.join((typeof copyDir === 'string'
			? copyDir
			: `${os.homedir()}/.cache/icon/`), pkg.version);
		const copyDistPath = path.join(copyDir, binName);
		if (!fs.existsSync(copyDistPath)) {
			fs.mkdirSync(copyDir, { recursive: true });
			fs.copyFileSync(binPath, copyDistPath);
		}
		return copyDistPath;
	}
	return binPath;
};
```

**Comment by sindresorhus** [comment]
See https://github.com/zeit/pkg/pull/751

It’s up to `pkg` to merge that PR.
