### ISSUE TITLE
WSL: `open` fails due to quoting issue

### ISSUE THREAD

**Issue by radar** [sindresorhus/open#165]
## Details

* WSL Version: Ubuntu, Version 2
* Open version: v7.0.0
* Browser version: Firefox 73.0b9

## Steps to reproduce

Open `node`, then:

```
const open = require("open")
open("http://localhost:3000", { wait: false })
```

## What I expect to happen

The browser starts up, and opens localhost:3000

## What actually happens:

![image](https://user-images.githubusercontent.com/2687/73222266-ee888880-41b6-11ea-80a8-a3ae0daad8ec.png)

## Other information

This works with Open v6.3.0.

I suspect commit 7ef15d29a8776737d2d097f02d117c2ec0439d58 is to blame for this issue.

**Comment by radar** [comment]
cc @Apochilles

**Comment by pluma** [comment]
Just tested this and removing the following line solves this issue:

```js
target = `"${target}"`;
```
