### ISSUE TITLE
How to check whether Firefox or Chrome is installed on Windows?

### ISSUE THREAD

**Issue by KerimG** [sindresorhus/open#167]
Hey all, 

I want to open a URL with either Chrome or Firefox and I have to know which one is available, because of the differences in their command line arguments. I tried wrapping the open funtion in a try/catch but that doesn't seem to work.

```js
try {
    await opn("http://localhost:12344", { app: "firefox" });
  } catch (error) {
    console.log("caught");
  }
```

Even if I were to catch it, windows shows the error message that the program in question doesn't exist. Basically this:

![image](https://user-images.githubusercontent.com/9061713/73453510-74016980-436c-11ea-9414-a374401605b2.png)

I figure I have to first check whether Chrome or Firefox are available. How would I do that?

**Comment by sindresorhus** [comment]
There's no easy cross-platform way to do this, unfortunately.

For Windows, I found this package: https://github.com/vweevers/win-detect-browsers 

If anyone has more info about this, please submit a tip to the readme.

**Comment by KerimG** [comment]
@sindresorhus 

I don't really need a cross-platform solution, at the moment. I think it's somewhat easy to check for available browsers in a *nix environment but it's a hassle in Windows. Looks like that win-detect-browsers works well, though. Thank you very much!
