### ISSUE TITLE
Error ENOTDIR when using yarn 2's pnp

### ISSUE THREAD

**Issue by ridho9** [sindresorhus/open#169]
I was debugging ENOTDIR error when this package is used to open browser by package `webpack-plugin-serve`. After a long debugging I tried to unplug this package (which effectively makes the package has a real node_modules folder) and it works. 

So I guess that the `command` variable is a bit confused when in a pnp environment and cant point to the xdg-open script path.

**Comment by sindresorhus** [comment]
Sorry, I have no intention of spending time on Yarn PnP problems. I would recommend opening an issue on https://github.com/yarnpkg/berry about this incompatibility. They are the ones breaking the whole ecosystem. They should also be the one to fix problems.

**Comment by ridho9** [comment]
Thank you for your response, I guess currently the only solution is just to unplug the package

**Comment by rbong** [comment]
Related: https://github.com/yarnpkg/berry/issues/856
