### ISSUE TITLE
Strips querystring from URL if it precedes with # in Windows 10 - Chrome

### ISSUE THREAD

**Issue by codef0rmer** [sindresorhus/open#17]
Following code works fine - opens the exact URL in chrome.

``` javascript
var open = require("opn");
open('http://codef0rmer.github.io/eShell/index.html#/1?name=foobar', {app: 'chrome'});
```

However, if Chrome is a default browser and it's not mentioned then both hash and querystrings are stripped.

``` javascript
var open = require("opn");
open('http://codef0rmer.github.io/eShell/index.html#/1?name=foobar');
```

Any idea why `spawn` strips querystring?

**Comment by watson** [comment]
My default browser is Safari, but I just checked and this doesn't seem to be an issue there. Which OS do you use?

**Comment by codef0rmer** [comment]
Make Chrome your default browser in Windows 10 and run 2nd snippet from a terminal to reproduce the issue.

**Comment by sindresorhus** [comment]
Works fine for me on Windows 8.1 with Chrome. I don't have Windows 10 to test on.

**Comment by codef0rmer** [comment]
@sindresorhus: It works fine on Windows 8 but not on Windows 10. Same issue even with node-open :-(

**Comment by codef0rmer** [comment]
@sindresorhus: After some testing, I realized the problem was `#` in the URL, it strips everything after that. I also noticed `target = target.replace(/&/g, '^&');` in your source and googled the entire web for `#` with no luck.

Just dark web is remaining now ;-)

**Comment by codef0rmer** [comment]
BTW, it's `"cmd /c "start http://codef0rmer.github.io/eShell/index.html#/1?name=foobar"` strips content followed by `#`.

**Comment by sindresorhus** [comment]
Does `cmd /c "start \"http://codef0rmer.github.io/eShell/index.html#/1?name=foobar\""` work?

**Comment by codef0rmer** [comment]
Nope.

![image](https://cloud.githubusercontent.com/assets/167227/10301083/73553916-6c1c-11e5-9b75-3254e42e2111.png)

**Comment by watson** [comment]
Seems to me that the escape chars (`\`) in front and back of the URL is messing things up. I'm not any good with Windows, but may try single quotes instead?, E.g:

```
cmd /c "start 'http://codef0rmer.github.io/eShell/index.html#/1?name=foobar'"
```

Or the reverse:

```
cmd /c 'start "http://codef0rmer.github.io/eShell/index.html#/1?name=foobar"'
```

**Comment by codef0rmer** [comment]
@watson: No luck - The same error.

**Comment by HansHammel** [comment]
is this closed cause
```
var open = require("opn");
open('http://codef0rmer.github.io/eShell/index.html#/1?name=foobar', {app: 'chrome'});
```
works for me on win10
btw: no quotes work from commandline (IE - default)
`cmd /c start http://codef0rmer.github.io/eShell/index.html#/1?name=foobar`
