### ISSUE TITLE
URLs with query string not working on WSL

### ISSUE THREAD

**Issue by tiagonapoli** [sindresorhus/open#170]
I'm trying the following snippet in WSL:
```ts
const open = require('open')
open('http://www.google.com.br/?a=1&b=2', { url: true, wait: false })
```
But the URL opened is `https://www.google.com.br/?a=1`. The URL is trimmed after the first `&`.

I'm suspecting the shell is interpreting the `&` as a "Run in background" directive

open: 7.0.2
OS:  Ubuntu 18.04 WSL on Windows 10

**Comment by sindresorhus** [comment]
// @pluma

**Comment by tiagonapoli** [comment]
The version `6.4.0` has a replace code for apparently escaping `&` characters when in WSL, and it opens the URL with the correct query string (`https://www.google.com.br/?a=1&b=2`):
https://github.com/sindresorhus/open/blob/37a769d6073862ab4a46c00b1a21b2ba814e68cf/index.js#L57-L59

**Comment by pluma** [comment]
That makes sense to me.

**Comment by tiagonapoli** [comment]
Unfortunately adding this escaping doesn't work for this case:
```
https://sindresorhus.com/?abc=123&def=456&ghi=with spaces
```
For some reason the URL opened is:
```
https://sindresorhus.com/?abc=123^&def=456^&ghi=with%20spaces
```
But it does work with:
```
https://sindresorhus.com/?abc=123&def=456
```

**Comment by tiagonapoli** [comment]
It seems that when there are spaces the url must not have &s escaped.
When there aren't spaces it needs. 😞 

I created a bash script under WSL and tested some scenarios, couldn't find a solution though:
```
#!/bin/bash
cmd.exe /s /c start "" "https://sindresorhus.com/?abc=123&def=456 a"
cmd.exe /s /c start "" "https://sindresorhus.com/?abc=123&def=456"
```

**Comment by tiagonapoli** [comment]
If that is indeed the case (no spaces == need escaping), encoding URLs would get rid of these spaces and then escaping &s would be a requiremet. Maybe if `url` is true the target URL could be sanitized in case of WSL. (not sure about win32)

**Comment by pluma** [comment]
@tiagonapoli can you try patching your local copy of the library and see if that works?

**Comment by tiagonapoli** [comment]
Escaping worked on WSL, but not on win32:

win32:
```
// Opens https://sindresorhus.com/?abc=123^&def=456
cmd.exe /s /c start "" "https://sindresorhus.com/?abc=123^&def=456" 

// Opens https://sindresorhus.com/?abc=123&def=456%20a
cmd.exe /s /c start "" "https://sindresorhus.com/?abc=123&def=456 a"

// Opens https://sindresorhus.com/?abc=123^&def=456%20a
cmd.exe /s /c start "" "https://sindresorhus.com/?abc=123^&def=456 a"
```

WSL:
```
// Opens https://sindresorhus.com/?abc=123&def=456
cmd.exe /s /c start "" "https://sindresorhus.com/?abc=123^&def=456" 

// Opens https://sindresorhus.com/?abc=123&def=456%20a
cmd.exe /s /c start "" "https://sindresorhus.com/?abc=123&def=456 a"

// Opens https://sindresorhus.com/?abc=123^&def=456%20a
cmd.exe /s /c start "" "https://sindresorhus.com/?abc=123^&def=456 a"
```

So apparently the problem is only on WSL, when there's no spaces in the URL. I opened a PR trying to fix this issue, didn't like how specific it got though - on WSL would be necessary to set the `url` option to work :(

**Comment by tiagonapoli** [comment]
@pluma @sindresorhus  Any thoughts?

**Comment by sindresorhus** [comment]
> Seems to me that the correct place to fix this is on WSL microsoft/WSL

Please open an issue there.
