### ISSUE TITLE
Reveal in Finder / Explorer

### ISSUE THREAD

**Issue by mifi** [sindresorhus/open#175]
When you have a file and you want to open Finder/Explorer etc with that file highlighted and in view.
I'm not sure if it's outside the scope of this package or even possible on Windows/Linux but for mac we can do this:

```bash
open -R /Users/mifi/Desktop/file.txt
```

**Comment by sindresorhus** [comment]
It's outside the scope since it's only possible on macOS.

**Comment by dheidelberger** [comment]
This is a really useful package, thanks for maintaining it. This can actually be done cross-platform. [On Windows](https://ss64.com/nt/explorer.html), you can do:
`explorer /select, [path to file]`

Linux definitely looks [more complicated](https://askubuntu.com/questions/133597/reveal-file-in-file-explorer).

**Comment by mifi** [comment]
@dheidelberger wanna make an npm package? 😁
