### ISSUE TITLE
Examples for opening with different browsers on different platforms

### ISSUE THREAD

**Issue by Jolg42** [sindresorhus/open#177]
I guess I'm not alone but I'm always struggling to remember exactly which app name to use on which platform.

So it looks like this:

`await open('https://github.com', {app: 'APP_NAME'});`

- On macOS, the value is the name of the app/browser
- On Linux, the value is the name of the binary
- On Windows, the value is the name of the .exe

| OS      | Browser             | APP_NAME      				|
| ------- | ------------------- | ----------------------------- |
|  macOS  | Chrome              | `Google Chrome`      			|
|         | Firefox             | `Firefox`                   	|
|         | Firefox (Developer) | `Firefox Developer Edition` 	|
|         | Safari              | `Safari`                    	|
| Windows | Chrome              | `Google Chrome`             	|
|         | Firefox             | `Firefox`                   	|
|         | Firefox (Developer) | `Firefox Developer Edition` 	|
|         | Brave               | `Brave`                     	|
|  Linux  | Chrome              | `google-chrome`             	|
|         | Firefox             | `firefox`                   	|
|         | Firefox (Developer) | `firefox-developer-edition` 	|
|         | Brave               | `brave`            	        |

Note that capitalization is important in all cases. 

Thanks to @madebysid for figuring it out 😉

**Comment by sindresorhus** [comment]
Thanks for writing this up. See https://github.com/sindresorhus/open/issues/116. I want to make it easier to launch commonly-used apps like browsers.

**Comment by iongion** [comment]
On Windows 10, this does not work

```open('http://localhost:5000/test-runner.html', { wait: true, app: 'Google Chrome' });```
![image](https://user-images.githubusercontent.com/867609/81173937-2581ed80-8fa1-11ea-83fc-a1cd3bbd435f.png)

But this does

```open('http://localhost:5000/test-runner.html', { wait: true, app: 'Chrome' });```

* The **wait** does not work for any of them
* They are installed in their default paths (no customization)

Firefox developer edition does not work with any of those above

**Comment by Jolg42** [comment]
\`On Windows, the value is the name of the .exe\`

@iongion Could you check the name of the .exe files?

**Comment by iongion** [comment]
Sure, chrome lowercase
![image](https://user-images.githubusercontent.com/867609/81175014-2287fc80-8fa3-11ea-9b42-6525d1c79e7e.png)
Edge like this
![image](https://user-images.githubusercontent.com/867609/81175053-2ddb2800-8fa3-11ea-9e84-f6f4453ffe86.png)
Firefox developer
![image](https://user-images.githubusercontent.com/867609/81175173-59f6a900-8fa3-11ea-91d2-f8d0c1268608.png)
Firefox
![image](https://user-images.githubusercontent.com/867609/81175208-6c70e280-8fa3-11ea-9188-5fe298e0b5e0.png)

**Comment by Jolg42** [comment]
@iongion In that case, try to use exactly that value `firefox` or `chrome` in lowercase here, that should work!

**Comment by iongion** [comment]
Can't something like this be used to detect paths on Windows 10 ?
https://github.com/igorskyflyer/npm-registry-apppaths

**Comment by mesqueeb** [comment]
@Jolg42 can you make a PR that adds this list to the README. I have to come back to this thread so much and send it to my colleagues etc so they can double check.

**Comment by Jolg42** [comment]
Looks like this issue is not completely needed anymore with https://github.com/sindresorhus/open/releases/tag/v8.0.0

Chrome and Firefox can now be used like this
https://github.com/sindresorhus/open#openapps
```
const open = require('open');

await open('https://google.com', {
	app: {
		name: open.apps.chrome // or open.apps.firefox
	}
});
```

**Comment by Richienb** [comment]
Should Safari and Brave also be added?

**Comment by Jolg42** [comment]
Safari for Windows (only runs on macOS) was discontinued so that sounds like an edge case (from a multiplatform point of view), but it could also be a convenient way to reference it.

Brave could be a good candidate I think, I don't know what the maintainers think about that.

**Comment by sindresorhus** [comment]
We could add Brave, Firefox Dev edition, and Chrome Canary, but not Safari.

**Comment by germancasares** [comment]
> 
> 
> Sure, chrome lowercase
> ![image](https://user-images.githubusercontent.com/867609/81175014-2287fc80-8fa3-11ea-9b42-6525d1c79e7e.png)
> Edge like this
> ![image](https://user-images.githubusercontent.com/867609/81175053-2ddb2800-8fa3-11ea-9e84-f6f4453ffe86.png)
> Firefox developer
> ![image](https://user-images.githubusercontent.com/867609/81175173-59f6a900-8fa3-11ea-91d2-f8d0c1268608.png)
> Firefox
> ![image](https://user-images.githubusercontent.com/867609/81175208-6c70e280-8fa3-11ea-9188-5fe298e0b5e0.png)

This thread is already closed, but I am struggling to open Firefox Dev on a Windows. The path doesn't seem to work :/

**Comment by Jolg42** [comment]
> This thread is already closed, but I am struggling to open Firefox Dev on a Windows. The path doesn't seem to work :/

@germancasares maybe you can share the code and version you're using that doesn't work?
