### ISSUE TITLE
Is there any callback when the URL has finished loading?

### ISSUE THREAD

**Issue by trusk89** [sindresorhus/open#178]
As the title says. I want to get some sort of callback when the URL has loaded, but it's not clear how to achieve that.

Thanks!

**Comment by sindresorhus** [comment]
There's no way to achieve this with `open`. On macOS, you might be able to use AppleScript for this, but I have no idea for other platforms. You'll also need a custom script for each browser.

**Comment by trusk89** [comment]
Thanks @sindresorhus!
