### ISSUE TITLE
Browser does not open when I push this code to Heroku

### ISSUE THREAD

**Issue by gbmahili** [sindresorhus/open#180]
I was hoping someone can help me.
I have a test Node/Express app, working perfectly on localhost.
Its sole purpose is to open a new browser with the Wikipedia page. 

However, when I push my code to Heroku, the Wikipedia page does not open in a new browser window.

Is there anyone else with this issue?
Here is the test code:
```
const express = require('express');
const app = express();
const open = require('open');
const port = process.env.PORT || 3000;
app.get('/', (req, res) => {
  open('https://www.wikipedia.org/')
    .then(d => console.log('---done', d))
    .catch(e => {
      console.log('---error', e)
    });

  res.send("Hello world")
  console.log('Home')
});

app.listen(port, () => console.log('App listening on 3000'));
```

**Comment by sindresorhus** [comment]
What's the point of opening a browser window on the Heroku instance? I think you're misunderstanding what this package does.

**Comment by gbmahili** [comment]
> What's the point of opening a browser window on the Heroku instance? I think you're misunderstanding what this package does.

Hi, thanks for replying.
I believe I am misunderstanding what this package does. Can you please provide clarification.
I am basically trying to upload videos on YouTube using Node and following this package instruction: (https://www.npmjs.com/package/youtube-api). This package uses opn. However, when I push my code to a server (testing on Heroku), the opn package does not open a new browser for me to Authenticate. It works well locally. Am I doing things wrong?

Thanks

**Comment by connorlurring** [comment]
@gbmahili 

This package is used to open a browser window locally on the machine that is running the code. When you push your code to Heroku, the code is running on the Heroku server rather than your own computer. 

This means the package will attempt to open a browser window on the Heroku instance, rather than locally on your own computer, which is why you are not seeing a window open on your machine.

**Comment by gbmahili** [comment]
@connorlurring Thanks for providing that feedback. Do you know of a way to achieve the goal described in my above comment? Thanks again.

**Comment by connorlurring** [comment]
@gbmahili 

I'd suggest that rather than using open, you use JavaScript or a button in your HTML page to redirect the user to the OAuth login page from your site.

**Comment by gbmahili** [comment]
@connorlurring Thanks a lot. I will give that a shot.
