### ISSUE TITLE
url option breaks encoded URLs

### ISSUE THREAD

**Issue by ltm** [sindresorhus/open#181]
The wrong URL will be opened when the `{url: true}` option is set and the URL contains encoded characters. This is particularly problematic when using reserved characters in query parameters (in practice this is common with base64-encoded values). For example:

```javascript
const open = require('open');

const url = new URL('https://httpbin.org/get')
url.searchParams.append('foo', '%');
url.searchParams.append('bar', '&');
url.searchParams.append('baz', '=');

console.log(url.href);
open(url.href, {url: false});
open(url.href, {url: true});
```

The valid string representation of this URL is https://httpbin.org/get?foo=%25&bar=%26&baz=%3D and when opened with `{url: false}` the service will echo the correct parameters:
```
"args": {
  "bar": "&", 
  "baz": "=", 
  "foo": "%"
},
```

However, when opened with `{url: true}` the values get double-encoded:
```
"args": {
  "bar": "%26", 
  "baz": "%3D", 
  "foo": "%25"
},
```

Since query string only gets escaped correctly on WSL when `{url: true}` is set (cf. #171), there's currently no way to open a URL containing reserved characters in the query string on WSL.

I'm thinking that a solution would be to only encode double-quotes, i.e.:

```javascript
if (options.url) {
	target = target.replace(/"/g, '%22');

	if (isWsl) {
		target = target.replace(/&/g, '^&');
	}
}
```

Alternatively:

```javascript
const url = require('url');

// ...

if (options.url) {
	target = url.parse(target).href;

	if (isWsl) {
		target = target.replace(/&/g, '^&');
	}
}
```

**Comment by sindresorhus** [comment]
// @herberttn

**Comment by ltm** [comment]
@sindresorhus @herberttn The change in #182 uses `url.URL` to parse and encode the URL which is supported since Node [v7.0.0, v6.13.0](https://nodejs.org/api/url.html#url_class_url). This will work for both encoded and unencoded URLs, but it will throw a `TypeError` if the target is not a valid URL.

```javascript
const url = require('url');

// ...

if (options.url) {
	target = new url.URL(target).href;

	if (isWsl) {
		target = target.replace(/&/g, '^&');
	}
}
```

**Comment by herberttn** [comment]
I do not see any reason not to move forward with this
