### ISSUE TITLE
Deno support?

### ISSUE THREAD

**Issue by andykais** [sindresorhus/open#212]
It would be great if I could use this module with [deno](https://deno.land/). There is currently no cross platform "open" tool for deno.

A common tool for porting applications to deno is [denoify](https://github.com/garronej/denoify)

**Comment by sindresorhus** [comment]
Sorry, I don't plan to support Deno in the near future. Anyone is free to reuse the code here though as long as they follow the MIT license requirements.

https://stackoverflow.com/questions/61821038/how-to-use-npm-module-in-deno
