### ISSUE TITLE
Node.js 12 is required but Node 10 is still tested and working

### ISSUE THREAD

**Issue by Jolg42** [sindresorhus/open#228]
I noticed the new 12.x requirement in release notes cde5c79

But also noticed tests are still running on 10.X and passing
https://github.com/sindresorhus/open/runs/2012436669?check_suite_focus=true

Would it be ok to change the requirement to `>=10` maybe?

**Comment by alan-agius4** [comment]
The reason being for this is that unit tests are not run in CI 😒
Only linting and DTS checks are done.

**Comment by Jolg42** [comment]
Note: I see 10 was removed from CI ✅ in https://github.com/sindresorhus/open/commit/59df90f1d8d6282af4162d7794957a84797888e7
