### ISSUE TITLE
v8.0.1: program arguments not being passed to Mac's open program

### ISSUE THREAD

**Issue by ericmandel** [sindresorhus/open#231]
The new {app: {name: "xxx", argument: "yyy"}} syntax doesn't appear to be passing arguments to the open program on a Mac.

Here is (correct) v7.4.1:

<img width="666" alt="v7 4 1" src="https://user-images.githubusercontent.com/3028875/109699882-15a24e00-7b5f-11eb-817f-989b03f337bd.png">

Here is v8.0.1, with the arguments not passed ... perhaps I've got the syntax wrong??

<img width="644" alt="v8 0 1" src="https://user-images.githubusercontent.com/3028875/109699936-2ce13b80-7b5f-11eb-962e-1981cb8580cb.png">

macOS: 10.15.7

**Comment by sindresorhus** [comment]
// @Richienb

**Comment by Richienb** [comment]
`arguments` is actually an array of strings.

**Comment by ericmandel** [comment]
@Richienb @sindresorhus Sorry, but this still does not work on a Mac, even with the correct calling sequence:
````
[~/tmp] eric% npm ls
tmp@ /Users/eric/tmp
└─┬ open@8.0.2
  ├── define-lazy-prop@2.0.0
  ├── is-docker@2.1.1
  └─┬ is-wsl@2.2.0
    └── is-docker@2.1.1 deduped

[~/tmp] eric% node
Welcome to Node.js v15.11.0.
Type ".help" for more information.

> const open = require('open');
undefined

> open('https://sindresorhus.com', {app: {name: 'google chrome', arguments: ['--incognito']}});
Promise {
  <ref *1> ChildProcess {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _closesNeeded: 3,
    _closesGot: 0,
    connected: false,
    signalCode: null,
    exitCode: null,
    killed: false,
    spawnfile: 'open',
    _handle: Process {
      onexit: [Function (anonymous)],
      pid: 27250,
      [Symbol(owner_symbol)]: [Circular *1]
    },
    spawnargs: [ 'open', '-a', 'google chrome', 'https://sindresorhus.com' ],
    pid: 27250,
````
