### ISSUE TITLE
Closes cmd/powershell when opening url

### ISSUE THREAD

**Issue by nutgaard** [sindresorhus/open#236]
Lib version: 8.0.3
Nodejs: 15.11.0
Window: Win 10 build 19042.804

Steps to reproduce;
```javascript
const open = require('open');
open('http://github.com');
```
Then: `node index.js` 

Expected behaviour;
1. Opens url in default browser
2. Cmd/powershell process is kept running.

Actual behaviour:
1. Opens url in default browser
2. Kills cmd/powershell process

**Comment by sindresorhus** [comment]
Is this a new issue in 8.0.3? If not, can you test some older versions?

**Comment by nutgaard** [comment]
Just tested it, and was on my way to update the issue. :D 

`open@8.0.2` works as expected.

**Comment by sindresorhus** [comment]
// @kykint

**Comment by kykint** [comment]
According to your code  - you don't use "wait: true" option. Without this option powershell shouldn't keep running.

**Comment by nutgaard** [comment]
I could understand it exiting out of the node-script sure. 
But killing the entire terminal-process seems a bit like over-reaching to be honest, but maybe that has been the expected behaviour all along?
Anyways, I'll test it out with `{wait: true}`.

As a side-note, shouldn't this have been a major-version bump? Pretty drastic change in behaviour for patch-bump.

**Comment by nutgaard** [comment]
Done some more testing outside of my project to easier isolate and test. 
By the looks of it then both of the snipplets below kills the cmd process when using `open@8.0.3`;

```
const open = require('open');
open("http://github.com", { wait: true });
```

```
const open = require('open');

(async () => {
  await open("http://github.com", { wait: true });
})();
```

**Comment by kykint** [comment]
I understood the problem. cmd window is not killed - It's just hidden. Will try to fix it

**Comment by kykint** [comment]
Maybe the best way is just add windows-only option, like "hiddenTerminal". Because there is another situation, when node.js application is started not from cmd. Then powershell creates one more window and it appears on top of all other applications and it is also not good. I can't find better solution yet.

**Comment by nutgaard** [comment]
I don't know which situations you're referring to (electron-app? pkg-bundled app?). 
But unless there is a reliable way of identifying those situations, then that seems like a better solution.

**Comment by kykint** [comment]
I tried to find a way, how to determine environment, but didn't find :( So, I've created a PR #238 with an addition option.

**Comment by adamtay** [comment]
Also encountered this issue on 8.0.4 with cmd disappearing when opening url. Downgrading to 8.0.2 has resolved it.

**Comment by imagitama** [comment]
Same issue for me and downgrading to 8.0.2 fixes it (I was on 8.0.5). Using Ubuntu for Windows and opening a URL in default browser with no options

**Comment by AnWeber** [comment]
> I don't know which situations you're referring to (electron-app? pkg-bundled app?).

I use `open` in my vscode extension to open the browser for the OAuth2 authorization code flow. On some installations this terminates the extension host of vscode, but not on all machines. The extension is [vscode-httpyac](https://marketplace.visualstudio.com/items?itemName=anweber.vscode-httpyac). I would prefer a setting to enable/ disable the closing mechanism. Downgrade to 8.0.2 fixed it for me.

**Comment by alan-agius4** [comment]
Had a similar report in Angular CLI https://github.com/angular/angular-cli/issues/20807
