### ISSUE TITLE
Unable to open when specifying `open.apps.chrome`

### ISSUE THREAD

**Issue by joeattardi** [sindresorhus/open#239]
I'm running macOS 10.15.7 and am having trouble with `open`.

A really simple test case for me is simply:

```
open('https://localhost', { app: { name: open.apps.chrome }});
```

Basically, nothing happens. I did some digging and debugging and the issue seems to be that the command open is trying to run:

```
open -a 'google chrome canary' 'https://localhost'
```

And my system is throwing the error:

```
Unable to find application named 'google chrome canary'
```

If I instead specify the app explicitly as just 'google chrome', it works.

Interestingly, this was working fine for me just yesterday and suddenly something is not working. Any ideas what the issue could be? Bad Chrome installation?

**Comment by sindresorhus** [comment]
// @Richienb
