### ISSUE TITLE
url option is gone, but it's linked in the readme

### ISSUE THREAD

**Issue by jcesarmobile** [sindresorhus/open#241]
On the Double-quotes on Windows section https://github.com/sindresorhus/open#double-quotes-on-windows

There is this comment about url option
> To make this caveat somewhat less impactful (at least for URLs), check out the url option. Double-quotes will be "preserved" when using it with an URL.

That links to https://github.com/sindresorhus/open#url
But the url option was removed on version 8, so the link is dead

So that part should probably be removed.
But considering it was there to make "this caveat somewhat less impactful", not sure if there is a better alternative now or if the Double quotes on Windows problem is gone on version 8 and the whole section can be removed.

**Comment by sindresorhus** [comment]
I think the whole section could be removed. @tim-stasse Correct?
