### ISSUE TITLE
open.apps.chrome is broken on Linux

### ISSUE THREAD

**Issue by pimterry** [sindresorhus/open#244]
https://github.com/sindresorhus/open/blob/01887ed979ded27a8c6f641485fea8c57e2d0972/index.js#L223-L255

On Linux, when this code is called:

* In `detectPlatformBinary`, `platformBinary` is the array of two Chrome string names
* That means the platform check in `detectPlatformBinary` passes, so it goes to `detectArchBinary(platformBinary)`
* In `detectArchBinary`, `binary` is still the array of Chrome names
* That means it's not a string, so the first test fails
* Then it's incorrectly treated as an object, destructuring to look up the name by architecture key, equivalently to `['google-chrome', 'google-chrome-stable']['x64']`.
* This clearly doesn't work. It returns undefined, so `detectArchBinary` throws `x64 is not supported`.

This will occur 100% of the time on Linux AFAICT. I suspect it should accept array values too at the start of `detectArchBinary`.

**Comment by sindresorhus** [comment]
// @Richienb

**Comment by pimterry** [comment]
Great work, thanks!
