### ISSUE TITLE
Powershell PR is causing Antivirus to trigger IDP.ALEXA.53 threat

### ISSUE THREAD

**Issue by JosephG3001** [sindresorhus/open#251]
[This PR from two days](https://github.com/sindresorhus/open/pull/250/commits/1fa48eeb171ee53decf2c5c7d61718ac158169e1) ago is causing antivirus to popup with IDP.ALEXA.53 threat.  

Posted the full details in [create-react-app](https://github.com/facebook/create-react-app/issues/10982).

**Comment by sindresorhus** [comment]
You should report this to your anti-virus vendor. It's clearly a false-positive.
