### ISSUE TITLE
Configure an environment variable for powershell path

### ISSUE THREAD

**Issue by gitfish** [sindresorhus/open#259]
Can we please update the code to configure a different powershell path?

E.g.
```
command = isWsl ?
			`${mountPoint}c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe` :
			`${process.env.SYSTEMROOT}\\System32\\WindowsPowerShell\\v1.0\\powershell`;
```

might be updated with something like:

```
command =  isWsl ?
		        (process.env.OPEN_LIB_POWERSHELL_PATH_WSL || `${mountPoint}c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe`) :
			(process.env.OPEN_LIB_POWERSHELL_PATH || `${process.env.SYSTEMROOT}\\System32\\WindowsPowerShell\\v1.0\\powershell`);
```

**Comment by gitfish** [comment]
I'll raise a PR if you think this is worthwile.

**Comment by sindresorhus** [comment]
Why?

**Comment by gitfish** [comment]
There is bill no why. But a further explanation: the built in powershell is
being blocked. I’m looking at pointing at powershell 7 (not blocked). Not
even sure powershell 7 takes the same arguments/parameters/flags. I believe
sfdx is ultimately making use of this lib to open the browser cross
platform.

Anyway, feel free to shoot the whole thing down.

Cheers,

**Comment by sindresorhus** [comment]
I don't think that's something we want to support.

**Comment by gitfish** [comment]
Thanks we.
