### ISSUE TITLE
How do I get the `stdout` information

### ISSUE THREAD

**Issue by gee1k** [sindresorhus/open#262]
Hello.

How do I get the `stdout` information, please?
I tried to use the `child_process` event but it didn't work.

What I want to do is to give information to the user when I specify that a browser is open and if that browser does not exist on the current system.

I'm looking forward to your reply. Thank you.

**Comment by sindresorhus** [comment]
```js
const {stdout} = await open(…);

stdout.pipe(process.stdout);
```
