### ISSUE TITLE
To open url on default browser with incognito mode on cross platforms 

### ISSUE THREAD

**Issue by hectorvp** [sindresorhus/open#266]
How do I open default browser  in incognito mode for cross platforms.
If I provide app explicitly, I won't be able to ensure whether that app (browser) is available or not.

```javascript
await open("https://www.google.com", { app: { name: open.apps.chrome , arguments: ["--incognito"] } });
```
In above example, it may be possible that chrome isn't installed and hence not default on linux machine.

Is something like this available anywhere??

```javascript
await open("https://www.google.com", {target: 'browser', 'flags':{incognito: true}});
```

**Comment by sindresorhus** [comment]
I suggest we add two more built-in constants:

- `open.apps.browser`
- `open.apps.browserPrivate` (this one would pass the correct flag)

PR welcome. But it's expected that you know what you're doing, and that you add tests, docs, and types.
