### ISSUE TITLE
open escapes # when there are spaces in the URL

### ISSUE THREAD

**Issue by martin-braun** [sindresorhus/open#274]
```js
open("https://google.com#test 123");
```

will open `https://google.com%23test%20123` when it should open `https://google.com#test%20123`. Edgy case, but threw me off. 

Would be nice if this would be fixed for the next poor guy searching for a way to disable escaping.

**Comment by sindresorhus** [comment]
What operating system?

**Comment by martin-braun** [comment]
@sindresorhus macOS 12.1 (21C52)

**Comment by sindresorhus** [comment]
Looking closer at this, it's working as expected. Unescaped space is not valid in an URL.

The native `open` also works this way:

```
command open 'https://google.com#test 123'
```

**Comment by martin-braun** [comment]
Well that's interesting. I thought I spotted a bug, but yes, it is no valid URL anyways. Well then it's fine I guess.
