### ISSUE TITLE
check if browser process is running event ?

### ISSUE THREAD

**Issue by GuitarHero1969** [sindresorhus/open#282]
This works great for my node express app:

`app.listen(3000, () => {
    console.log('Serving on port 3000...');
    open('http://localhost:3000');
});`

Just one problem, if I restart the node server, it opens a new instance / tab in Chrome.
I would like to be able just to cause a browser refresh instead within the above code.
Anyway to achieve this ?

**Comment by sindresorhus** [comment]
Duplicate of #256
