### ISSUE TITLE
It does not work if we package the app with PKG and create a service with NSSM

### ISSUE THREAD

**Issue by indice** [sindresorhus/open#285]
It does not work if we package the app with PKG and create a service with NSSM

C:\Windows\System32\WindowsPowerShell\v1.0\powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand <encode>

**Comment by sindresorhus** [comment]
> It does not work if we package the app with PKG

Problems with packaging should be reported on the `pkg` issue tracker. This package works in normal Node.js environments.
