### ISSUE TITLE
Avoid losing focus

### ISSUE THREAD

**Issue by danhper** [sindresorhus/open#3]
Hi,
I am using this module with Grunt to [display errors in the browser](https://github.com/claudetech/grunt-brerror)
while coding. However, the focus (on the editor) is lost after opening the browser, which is not very handy.
It would be nice if there could be an option to disable this behavior, but I am not sure
how it could be implemented cross-platform. For OS X, passing `-g` to the `open` command
should be ok, but I cannot find any equivalent for `xdg-open`.
Any ideas?

**Comment by sunknudsen** [comment]
@sindresorhus Would it be acceptable to implement a focus option that only works on Darwin to trigger `cliArguments.push('-g');`? I totally agree with @danhper that there are use cases where focusing a browser for instance isn’t optimal.

**Comment by sindresorhus** [comment]
Sure, PR welcome.

**Comment by sunknudsen** [comment]
@sindresorhus [PR](https://github.com/sindresorhus/open/pull/126) is out. Didn’t bump the version in case you prefer to handle that. Thanks!
