### ISSUE TITLE
esm support

### ISSUE THREAD

**Issue by peterpeterparker** [sindresorhus/open#302]
Hi,

I have trouble to using `open` in my Node esm library because it relies on `__dirname`.

```
// Path to included `xdg-open`.
const localXdgOpenPath = path.join(__dirname, 'xdg-open');
```

At runtime I get following issue:

> ReferenceError: __dirname is not defined in ES module scope

Is there a way to polyfill it to support both cjs and esm?

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/open/releases/tag/v9.0.0

**Comment by peterpeterparker** [comment]
Awesome, works like a charm. Thanks!
