### ISSUE TITLE
Make powershell EncodedCommand optional

### ISSUE THREAD

**Issue by adamperrry** [sindresorhus/open#304]
The EncodedCommand aspect of the windows PowerShell is causing some antivirus software to flag the command for some of our users. Is there any chance we could get an option to make that optional? I understand it's in there to allow special characters in the URL, but I think they'd be willing to accept that.

**Comment by sindresorhus** [comment]
I'm not going to make any changes here because of faulty anti-virus software. I recommend reporting the false-positive to the anti-virus software developers.
