### ISSUE TITLE
how to use it in Vite + Vue3?

### ISSUE THREAD

**Issue by will-s-zhang** [sindresorhus/open#311]
when i use it in Vite + Vue3, i received the following error message.
Ucaught TypeError: os3.homedir is not a function
    at node_modules/untildify/index.js (index.js:4:26)
    at __require (chunk-4EOJPDL2.js?v=4eb61dd6:8:50)
    at index.js:4:23
<img width="466" alt="image" src="https://user-images.githubusercontent.com/116798641/231336271-38af6353-d8c7-4698-812e-a8ddf107d25d.png">

**Comment by sindresorhus** [comment]
This would be a question for the Vite issue tracker.
