### ISSUE TITLE
Release v9.1.1 (Nodejs v20 fix)

### ISSUE THREAD

**Issue by yandeu** [sindresorhus/open#314]
Please release a new version because the Nodejs v20 test fails with the `xo` dependency version `^0.53.1`.

This has been fixed in https://github.com/sindresorhus/open/commit/ba6e43bde17f150286d002f5156c4ea89720c4b8.

Thanks!

**Comment by sindresorhus** [comment]
It's a dev dependency. It has no effect on the published version.

**Comment by yandeu** [comment]
Right 🤣
