### ISSUE TITLE
default browser not found (linux)

### ISSUE THREAD

**Issue by bugsounet** [sindresorhus/open#329]
Hi, I try to upgrade to v10.0.1

I just see this error

`Error: Google Chrome is not supported as a default browser`

For testing I use this:
```js
  open('https://www.google.fr', {
	  app: {
		name: apps.browser
	  },
	  wait: true
  });
```

and by using ` open('https://www.google.fr')` it's not works too (open nothing)

I debug `const browser = await defaultBrowser();` and  I just see this result: `debug-browser { name: 'Google Chrome', id: 'google-chrome.desktop\n' }`

maybe it's `\n` in the end of `google-chrome.desktop`

Note it's work perfectly in v9.1.x

@bugsounet

**Comment by sindresorhus** [comment]
The dependency has been fixed, so just remove `node_modules` and reinstall to get it.

https://github.com/sindresorhus/default-browser/releases/tag/v5.2.1

**Comment by bugsounet** [comment]
Thx, I will test as soon as possible ;)

**Comment by bugsounet** [comment]
* `apps.browser` works, fine !

* `open('https://www.google.fr')` don't works :/

I debug command to launch `xdg-open`, for me it's good ;)
```
path: /patch/to/node_modules/open/xdg-open
cliArguments: [ 'https://www.google.fr' ]
childProcessOptions: { stdio: 'ignore', detached: true }
```
I test xdg-open command line and i get this result:

```
/patch/to/node_modules/open/xdg-open https://www.google.fr

/patch/to/node_modules/open/xdg-open: 592: detectDE: not found
/patch/to/node_modules/open/xdg-open: 598: DEBUG: not found
/patch/to/node_modules/open/xdg-open: 506: has_display: not found
/patch/to/node_modules/open/xdg-open: 517: has_display: not found
/patch/to/node_modules/open/xdg-open: 449: www-browser: not found
/patch/to/node_modules/open/xdg-open: 449: links2: not found
/patch/to/node_modules/open/xdg-open: 449: elinks: not found
/patch/to/node_modules/open/xdg-open: 449: links: not found
/patch/to/node_modules/open/xdg-open: 449: lynx: not found
/patch/to/node_modules/open/xdg-open: 449: w3m: not found
/patch/to/node_modules/open/xdg-open: 524: exit_failure_operation_impossible: not found
```
some commands are missing !?

Note: same command  works with v9.1.x

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/open/releases/tag/v10.0.2

**Comment by bugsounet** [comment]
Perfect !

Thx @sindresorhus
