### ISSUE TITLE
[ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by LucileGrnd** [sindresorhus/open#340]
Hello I have this issue when I upgrade open to the latest version that I didnt have before:

- I am using an electron app

[ERR_REQUIRE_ESM]: require() of ES Module [...path]\node_modules\open\index.js from [component]\internal-window.js not supported

Any idea?

Thank you

**Comment by LucileGrnd** [comment]
Warning: This package is native [ESM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) and no longer provides a CommonJS export. If your project uses CommonJS, you will have to [convert to ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) or use the [dynamic import()](https://v8.dev/features/dynamic-import) function. Please don't open issues for questions regarding CommonJS / ESM.

**Comment by nfgaetest** [comment]
I also faced this issue.
Using 8.4.2 could simply resolved it.

```
  "dependencies": {
       :
    "open": "^8.4.2",
       :
  }
```

**Comment by alxndrsn** [comment]
> I also faced this issue. Downgrading to 8.4.2 could simply resolved it.
> 
> ```
>   "dependencies": {
>        :
>     "open": "^8.4.2",
>        :
>   }
> ```

This is correct, but could be more general.

ESM support was mandated in [v9](https://github.com/sindresorhus/open/releases/tag/v9.0.0):

> This package is now pure ESM. Please [read this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

So for new users, `npm install open@8` or `yarn install open@8` should work.

It might be helpful to include this in the README, e.g. [`node-fetch`](https://www.npmjs.com/package/node-fetch#commonjs) says:

> If you cannot switch to ESM, please use v2 which remains compatible with CommonJS. Critical bug fixes will continue to be published for v2.
> ...
