### ISSUE TITLE
open visible=none,toolbar=no,status=no,menubar=no,scrollbars=no,resizable=no

### ISSUE THREAD

**Issue by matteoannibali** [sindresorhus/open#90]
it's possible to do?

**Comment by sindresorhus** [comment]
This issue needs a proper title and a better explanation of what you're looking for.

**Comment by matteoannibali** [comment]
Sorry!
I would like to open an hidden or minimized windows.

thanks!

**Comment by sindresorhus** [comment]
You can pass app-specific arguments, but it's still not clear exactly what `visible=none,toolbar=no,status=no,menubar=no,scrollbars=no,resizable=no` is for.
