### ISSUE TITLE
Never call callback on Mac os

### ISSUE THREAD

**Issue by Lilipi** [sindresorhus/open#91]
Hello,

I've got a problem on Mac OS. Here is my code : 

```
...
.then(function() {
    var opn = require('opn');
    return opn(url);
})
.then(function() {
         MessageService.success("Document ouvert");
         return;
     });
```

It works fine on Windows, but on Mac OS, the callback (messageService.success ...) is never called.

Can anyone help me ?

Thanks

**Comment by Bjornskjald** [comment]
Probably related to #92.

**Comment by znevrly** [comment]
Hi, please any update?

**Comment by DanielRuf** [comment]
Still the same. On Windows my CLI app exits after I call opn, on macOS it waits and does not exit / return.

**Comment by DanielRuf** [comment]
Looks like the `-W` flag never fires an exit code unless we close the opened browser / app.

**Comment by DanielRuf** [comment]
Try `opn(target, {wait: false})`.

**Comment by sindresorhus** [comment]
From the docs:

> Wait for the **opened app** to exit before fulfilling the promise.

As far as I know, there's no way to wait for a window of the app to close.

**Comment by sindresorhus** [comment]
In hindsight, it would probably have been better to make the `wait` option `false` by default.

**Comment by DanielRuf** [comment]
The assumption in general is to have the same behavior on all platforms (which is not the case as for Windows we have to manually set some application name) and to be consistent by default (without any further configuration).

And I think this is the reason why I and others tripped over this.

And you are right, we should have read the docs and check the default values.
